from PyQt5 import QtWidgets, QtGui, QtCore, Qt
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QFileDialog

from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 535)
        Form.setMinimumSize(531,535)
        Form.setMaximumSize(531,535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("formikonu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color:lightblue")
        self.url = QtWidgets.QLineEdit(Form)
        self.url.setGeometry(QtCore.QRect(20, 160, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.url.setFont(font)
        self.url.setObjectName("url")
        self.radio1 = QtWidgets.QRadioButton(Form)
        self.radio1.setGeometry(QtCore.QRect(200, 220, 95, 20))
        self.radio1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("radiovideo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio1.setIcon(icon1)
        self.radio1.setObjectName("radio1")
        self.radio2 = QtWidgets.QRadioButton(Form)
        self.radio2.setGeometry(QtCore.QRect(300, 220, 95, 20))
        self.radio2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("radioses.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio2.setIcon(icon2)
        self.radio2.setObjectName("radio2")
        self.cozunurluk = QtWidgets.QComboBox(Form)
        self.cozunurluk.setGeometry(QtCore.QRect(30, 260, 471, 21))
        self.cozunurluk.setObjectName("cozunurluk")
        self.cubuk = QtWidgets.QProgressBar(Form)
        self.cubuk.setGeometry(QtCore.QRect(20, 300, 491, 23))
        self.cubuk.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cubuk.setFont(font)
        self.cubuk.setProperty("value", 0)
        self.cubuk.setTextVisible(True)
        self.cubuk.setOrientation(QtCore.Qt.Horizontal)
        self.cubuk.setInvertedAppearance(False)
        self.cubuk.setObjectName("cubuk")
        self.kaydet = QtWidgets.QLineEdit(Form)
        self.kaydet.setGeometry(QtCore.QRect(20, 340, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.kaydet.setFont(font)
        self.kaydet.setDragEnabled(False)
        self.kaydet.setReadOnly(True)
        self.kaydet.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.kaydet.setClearButtonEnabled(False)
        self.kaydet.setObjectName("kaydet")
        self.kaydetB = QtWidgets.QPushButton(Form)
        self.kaydetB.setGeometry(QtCore.QRect(460, 340, 51, 31))
        self.kaydetB.setStyleSheet("background-color:silver")
        self.kaydetB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("kaydetb.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kaydetB.setIcon(icon3)
        self.kaydetB.setObjectName("kaydetB")
        self.indirme = QtWidgets.QPushButton(Form)
        self.indirme.setGeometry(QtCore.QRect(120, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.indirme.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indirme.setIcon(icon4)
        self.indirme.setObjectName("indirme")
        self.indirme2 = QtWidgets.QPushButton(Form)
        self.indirme2.setGeometry(QtCore.QRect(260, 390, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.indirme2.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("apple_music_android_logo_icon_134021.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indirme2.setIcon(icon5)
        self.indirme2.setObjectName("indirme2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 460, 131, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1441800904_YouTube-02_47024.ico"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 131, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("1441800917_youtube_47022.ico"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 20, 131, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("1.ico"))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "YouTube İndirme"))
        self.url.setPlaceholderText(_translate("Form", "URL: https://www.youtube.com/watch?v=LwutVdCE4Gc"))
        self.kaydet.setPlaceholderText(_translate("Form", "  Kaydetme konumu için ---->>>>"))
        self.indirme.setText(_translate("Form", "Video"))
        self.indirme2.setText(_translate("Form", "Ses"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
